version: "3.1"

services:
  db:
    platform: linux/x86_64
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
